filter:
  paths: ["src/main/php/*", "tests/*"]
  excluded_paths: []

build:
    environment:
        php:
            version: 7.2.0
    tests:
        override:
            -
                command: './vendor/bin/phpunit --configuration build/phpunit/phpunit.travis.xml'
                coverage:
                    file: 'build/phpunit/data/clover.xml'
                    format: 'clover'

checks:
    php:
        code_rating: true
        duplication: true