language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
  fast_finish: true

sudo: false

env:
    global:
        TEST_CONFIG="build/phpunit/phpunit.xml.dist"

before_script:
  - composer self-update
  - if [ $DEPENDENCIES = low ] ; then composer update --prefer-dist --prefer-lowest --prefer-stable ; fi
  - if [ ! $DEPENDENCIES ] ; then composer install ; fi

script:
  - if [ $TRAVIS_PHP_VERSION != 7.1 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG ; fi
  - if [ $TRAVIS_PHP_VERSION  = 7.1 ]; then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG --colors --coverage-text ; fi


after_success:
  - travis_retry php vendor/bin/php-coveralls -v
